version: 1
formatters:
        generic:
                format: > 
                        %(asctime)s
                        %(levelname)-5.5s
                        [%(name)s]
                        [%(threadName)s]
                        %(message)s
loggers:
        root:
                level: WARN
                handlers: [console]
        mpd:
                level: DEBUG
                handlers: [sqlalchemy]
                qualname: mpd
        ydl:
                level: INFO
                handlers: [sqlalchemy]
                qualname: ydl
        sqlalchemy:
                # INFO logs SQL queries
                # DEBUG logs queries and results
                # WARN logs neither
                level: WARN
                qualname: sqlalchemy.engine
        controller:
                level: DEBUG
                handlers: [sqlalchemy]
                qualname: controller
handlers:
        console:
                class: logging.StreamHandler
                formatter: generic
                level: NOTSET
                stream: ext://sys.stderr
        sqlalchemy:
                class: handlers.SQLAlchemyHandler
                level: NOTSET
                formatter: generic
